### ISSUE TITLE
D@RE License Error with ECS CE

### ISSUE THREAD

**Issue by spiegela** [djannot/ecsui#5]
I'm getting an error when attempting to create a bucket via S3 using ECS community edition:

```xml
<Error>
  <Code>Server side encryption (D@RE) is not supported</Code>
  <Message>D@RE jar/license is unavailable hence server side encryption requests are not supported.</Message>
  <XemcRequestId>DARE</XemcRequestId>
</Error>
Close
```

I have the encryption option disabled in the create request:
![image](https://cloud.githubusercontent.com/assets/3212/23999402/500cea90-0a26-11e7-85ab-c68ae74a88e3.png)

Perhaps, when the D@RE license isn't installed, the `x-emc-server-side-encryption-enabled` option must be excluded from the request, even if it's set to `false`?

**Comment by djannot** [comment]
@spiegela Yes, this is an ECS bug. I have a Jira opened for it.
I didn't modify my code as I don't expect many users to use my tool with an ECS that doesn't have the D@RE license (which is free of charge)

**Comment by spiegela** [comment]
Cool. Too bad the ECS CE doesn't include the D@RE license. 😢

I'll be testing with the customer later today, and they do have D@RE loaded.

**Comment by djannot** [comment]
I'll ask if we can change the license we provide with it then
